config/routes.rb
Consultancy::Application.routes.draw do

  root 'home#index'
  get 'about' => "home#about"
  get 'services' => "home#services"
  get 'ourclients' => "home#ourclients"
  get 'contact' => "home#contact"

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<body style="background-color:#3B0B0B">
<div class="container" style="width:950px; height:550px; border:10px dotted blue; background-color: #D0FA58";>
<h2> <font color="#FA5858"> Ray of Hope Consultancy</font></h2>
&nbsp
&nbsp
&nbsp
&nbsp
                <font color="blue">Ray Of Hope Consultancy</font>
                various companies across verticals. <font color="blue">Ray Of Hope Consultancy</font> is based out of Bangalore &amp; 
                services clients across the country &amp; abroad. Since our inception we have been 
                in the business scenario with a mission of serving the companies with the speed 
                and quality that is required. It is a dream relished by our team of 
                professionals with varied experiences related to the service industry. Spurred 
                on by the experience and expertise in talent search and rehabilitation of human 
                resources, we have been providing the support to our esteemed clients to their 
                satisfaction. We strongly believe that quality is a process not an end result. 
                Therefore we have selected highly professional recruiters with strong technical 
                background. . They are with <font color="blue">Ray Of Hope Consultancy</font> Services not only because of their 
                experience and expertise, but also their desire to excel in the field of proper 
                deployment of resources. Thus it is the result of their knowledge and rich 
                experience, that we are able to find the right person at the right time and also 
                at the right price.<font color="blue">Ray Of Hope Consultancy</font> was founded in 2005.
</div>

app/views/home/contact.html.erb
<body style="background-color:#3B0B0B">
<div class="container" style="width:950px; height:550px; border:10px dotted blue; background-color: #D0FA58";>
<h2> <font color="#FA5858">Contact Us</font></h2>
<p style="font-weight: bold">
                    Ray Of Hope Consultancy
                </p>
                <p style="padding-left:10px">
                    <font face="Arial" size="2">#17,1st main,MSR layout<br />
                    Marathahalli<br />
                    <b>Landmark:</b> Next to Aroma Bakery,Marathahalli Bridge<br />
                    Bangalore 560037</font></p>
                <p style="padding-left:10px">
                    <font face="Arial" size="2"><b>Contact No :</b>8050664775</font><br />
                    <br />
                    <span class="creative-contact-sub"><b>E-mail:</b><br />
                        <a href="mailto:snigdha@rayofhopeconsultancy.co.in">snigdha@rayofhopeconsultancy.co.in</a><br />
                        <a href="mailto:rayofhope.hr@gmail.com">rayofhope.hr@gmail.com</a><br />
                    </span>
                </p>

</div>

app/views/home/index.html.erb
<body style="background-color:#3B0B0B">
<div class="container" style="width:950px; height:550px; border:10px dotted blue; background-color: #D0FA58";>
<h2> <font color="#FA5858"> Ray of Hope Consultancy</font></h2>
<p><font color="Blue"> &nbsp Ray Of Hope Consultancy</font> is a Bangalore based recruitment company providing effective end to end recruitment solutions for organizations in India and abroad.</p>
<p style="text-align:right"><a href = "<%= about_path %>">Read more...</a></p>
<h2> <font color="#FA5858"> Vision</font></h2>
<p> &nbsp We believe in establishing long-term relationship with our customers by consistently delivering creative and value-adding solutions and services of high quality.</p>
<p style="text-align:right"><a href = "<%= about_path %>">Read more...</a></p>
<h2> <font color="#FA5858"> Clients </font></h2>
<p>&nbsp Recognizing, respecting and admiring the hard-earned expertise of client organizations and candidates, through courteous and professional relationships at all times.</p>
<p style="text-align:right"><a href = "<%= ourclients_path %>">Read more...</a></p>
<h2> <font color="#FA5858"> Services </font></h2>
<p>&nbsp We specialize in the recruitment and placement of specialists in the Information Technology area such as analysts, programmers, designers, administrators, Project,Leaders and Managers.</p>
<p style="text-align:right"><a href = "<%= services_path %>">Read more...</a></p>
</div> <!-- /container -->
</body>

app/views/home/ourclients.html.erb
<body style="background-color:#3B0B0B">
<div class="container" style="width:950px; height:550px; border:10px dotted blue; background-color: #D0FA58";>
<h2> <font color="#FA5858">Our Clients</font></h2>
<p>Please <a href="<%= contact_path %>">Contact Us</a> to know about our clients.</p>

app/views/home/services.html.erb
<body style="background-color:#3B0B0B">
<div class="container" style="width:950px; height:550px; border:10px dotted blue; background-color: #D0FA58";>
<h2> <font color="#FA5858">Services</font></h2>
<p>
        We specialize in the recruitment and placement of specialists in the Information
        Technology area such as analysts, programmers, designers, administrators, Project
        Leaders and Managers. We provide a career matching service for IT professionals
        and potential employers by maintaining a talent repository of professionals in the
        IT area and continually updating the same.</p>
<p>
        We
        cater not only to the requirement of technical skills that our client requires of
        the candidate but cultural and attitudinal requisites as well. Selection, pre-screening
        and the value proposition: Assisted by an expert team of IT and industry professionals
        in the process, creative, keeping in line with its mission statement, conducts a
        preliminary pre-selection of the prospective IT employee, which consists of evaluation
        of technical skills as well as behavioral and attitudinal attributes. As part of
        our services in IT recruiting, we provide both intensive as well as extensive personality,
        communication and presentation skills enhancement programs for all IT professionals
        recruited through us, requiring these inputs in their assignments - especially geared
        for cross ethnic-cultural work environments.The skills which we focus on include
        :</p>
    <h4>
        Java:</h4>
    <p>
        JAVA, JSP, SERVLETS, JAVASCRIPT, J2EE, Ejb, LINUX, XML, UML, WEBLOGIC, WEBSPHERE,
        SWING, STRUTS, PL/SQL, LOTUS NOTES.. ETC.</p>
    <h4>
        Telecom / Networking:</h4>
    <p>
        SS7, VOIP, SIP MEGACO, MGCP IS41, CDMA, UDP, MOBILE APPLICATION, USER INTERFACE,
        KERNEL PROGRAMMING, SNMP/NMS/EMS, GSM, GPRS, PROTOCOL, EMS, VSAT, codecs.. ETC.</p>
    <h4>
        Embedded:</h4>
    <p>
        FPGA, XLINUX, FIRMWARE, RTOS, DIGITAL SIGNAL PROCESSING, RTL DEVELOPMENT, Device
        driver,BOARD DESIGN, VLSI VERIFICATION, VALIDATION DEVICE DRIVERS ETC. SYSTEM ADMIN
        :WINDOWS, UNIX(SOLARIES, AIX, HPUX),SERVER, LINUX, DESKTOP.. ETC.</p>
    <h4>
        Others:</h4>
    <p>
        DATA WARE HOUSING, SAP, .NET, TECHNICAL SUPPORT, BUSINEESS ANALYST, BUSINESS DEVELOPMENT,
        PRE-SALES MARKETING.. ETC.</p>
</div>

app/views/layouts/application.html.erb
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Ray Of Hope Consultancy</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">Ray Of Hope Consultancy</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="<%= root_path %>">Home</a></li>
              <li><a href="<%= about_path %>">About</a></li>
              <li><a href="<%= services_path %>">Services</a></li>
              <li><a href="%= uploadresume_path %>">Upload Resume</a></li>
              <li><a href="<%= ourclients_path %>">Our Clients</a></li>
              <li><a href="<%= contact_path %>">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
  <%= image_tag "" %> 
	<%= yield %>
  </body>
</html>